# Generated by Django 6.0.4 on 2026-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apsisrequest_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='core.profile'),
        ),
    ]
