# Generated by Django 6.0.4 on 2026-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_allowed_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='apsisrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='target_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allocated_products',
            field=models.ManyToManyField(blank=True, related_name='allocated_to', to='core.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('IT_TECHNICIAN', 'IT Technician'), ('REQUESTER', 'Requester'), ('VIEWER', 'Viewer')], default='REQUESTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
