# Generated by Django 6.0.4 on 2026-04-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apsisrequest_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apsisrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='apsisrequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='apsisrequest',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='apsisrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='apsisrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='target_user_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='target_user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apsisrequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allocated_products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='allowed_profiles',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('IT_TECHNICIAN', 'Technician'), ('REQUESTER', 'Requester'), ('VIEWER', 'Viewer')], default='REQUESTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove')], max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.apsisrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='ApsisRequestItem',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allowed_profiles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
