# Generated by Django 6.0.4 on 2026-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apsisrequest_department_apsisrequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apsisrequest',
            name='target_gps_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gps_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('IT_TECHNICIAN', 'Technician'), ('REQUESTER', 'Requester'), ('VIEWER', 'Viewer'), ('BENEFICIARY', 'Beneficiary')], default='REQUESTER', max_length=20),
        ),
    ]
